### ISSUE TITLE
[App Support] Native Podcast app

### ISSUE THREAD

**Issue by antipoet** [Stillness-2/beardie#19]
Would it be possible to add the native Apple Podcast app as well? 

So grateful to see this app getting support again, thanks!

**Comment by Stillness-2** [comment]
Apple Podcasts is not written with applescript support, so it's hard to do full control. I will think...

**Comment by panosru** [comment]
Hi, may I ask, is the Apple Podcasts app now supported after this commit, because I'm unable to find it in the strategies list?

Thanks!

**Comment by Stillness-2** [comment]
@panosru you may check beta version in `releases` sections

**Comment by panosru** [comment]
The play/pause button works for Apple Podcasts but only when the app is focused, is it possible to make it work even when the app isn't focused? 

Thanks!

**Comment by Stillness-2** [comment]
@panosru "is focused" - what that means actually? 
In my tests all worked as expected.

**Comment by panosru** [comment]
> "is focused" - what that means actually?

When an application is selected, that state is called "focused" meaning that you are on that application currently. When you select another application, then the previous application is out of focus.

When I have podcasts selected I can use the media buttons of my keyboard fine, but once I select another application or minimise apple podcasts, the media buttons aren't working anymore, they only work while in focus.

**Comment by Stillness-2** [comment]
Very strange behaviour, i can't repeat this issue.
I need more info... OS version, Podcasts app version, Beardie app version... 

Is the Podcasts app in list, like on this picture?
![image](https://user-images.githubusercontent.com/12689/129458779-994c4a32-e5b3-4749-a863-7b6d0ed847a8.png)

**Comment by panosru** [comment]
![image](https://user-images.githubusercontent.com/400362/129458840-6d013702-571e-4137-afd1-7d8c4fc5492b.png)
![image](https://user-images.githubusercontent.com/400362/129458851-946893aa-95e2-4004-ad19-5f4626dd0ae4.png)
![image](https://user-images.githubusercontent.com/400362/129458860-b7f775a0-b8bf-488e-b577-205363fe1b9f.png)
![image](https://user-images.githubusercontent.com/400362/129458874-e83f759d-1f03-42fa-9586-c4a47b1b6997.png)

I did a bit more testing and I can now see that the issue occurs when I switch space. For example, I have podcasts running in the background and I switch space to a fullscreen browser or another app, then the media buttons are not working.

**Comment by Stillness-2** [comment]
@panosru 
Sad ... Yes, at least in the latest version of Mac OS it does not work. Other adapters for applications that do not support applescript are also affected by this bug: Deezer, Tidal, Apple Podcasts!!! : (((
Apple is not the same... :(
I do not know how to fix this on my part, except to remove support for these players from the application. :(

**Comment by panosru** [comment]
@Stillness-2, it's not your fault that Apple f@ck up... Apple Script isn't supported by Apple Podcasts, just a sad lol... Not even M$ does that crap.

Anyways, I think it's not worth removing the feature, just place an asterisk for the affected apps and mention in the documentation that the apps marked with an asterisk are partially supported so people won't create new pointless issues.

Thanks for the try though!

**Comment by panosru** [comment]
Doing a bit more checking, since I have a 5 monitor setup, I found out that the issue only exists when on the main screen you are on a full-screen app. Basically, if your main screen doesn't have a fullscreen app currently, then the media keys are working fine across all monitors and spaces, even if Apple Podcasts is minimised or on another space.

Also, on the main screen, you may have fullscreen apps, as long as the fullscreen app of the main screen isn't focused. Having a fullscreen app focused on any other monitor, except the main, doesn't disturb the workflow of beardie and you can control Apple Podcasts.

I hope that description makes sense and maybe it can help somehow.

**Comment by Stillness-2** [comment]
Unfortunately, it won't help. As I wrote above, I do not know how to get around the feature of the API from the Apple. There is a function `AXUIElementPerformAction` from the API Accessibility. It allows you to "click" on menu items of another application. If an any application in fullscreen mode is currently in focus, then this function works without errors as usual, but in fact it does not do its job. That is, even the return of the function tells me that it is as if the action has been performed, although it is not. :)

**Comment by panosru** [comment]
Ah, I see, crap... So it is an API issue then, unfortunately, I'm not familiar with Apple's SDK to help somehow, but I wonder if what you describe is by design or a bug, maybe it is worth submitting it as a bug to Apple? Who knows, in a couple of decades we may get a fix from them! haha

So far, as a workaround, what I do is just create a new space and run the app I want maximised but not in fullscreen, that way at least I can play/pause the Apple Podcasts, so please, do not remove the support :)
