### ISSUE TITLE
Tidal Desktop support

### ISSUE THREAD

**Issue by Amplificator** [Stillness-2/beardie#4]
Is it possible to get this supported? On BeardedSpice it was listed as supported but never worked, perhaps it can be fixed?

Thanks :)

**Comment by Stillness-2** [comment]
@Amplificator I will think about it...

**Comment by Stillness-2** [comment]
@Amplificator Only basic functionality can be done. Since TIDAL Desktop does not provide API for control, such as support for commands via AppleScript. It is very disappointing that lately, it is customary to write under-applications on some Electron. Good manners have been canceled today. :)
Will not work: info about the current track, volume control via volume keys in the TIDAL Desktop, adding to My Collection
